### ISSUE TITLE
Live site down

### ISSUE THREAD

**Issue by lodenrogue** [sacylkowski/tavern-masters#10]
Seems the link to the live site in the README is down or pointing to the wrong location: https://github.com/sacylkowski/tavern-masters/blob/main

**Comment by truppeiner** [comment]
Hey, we appreciate you reaching out to help but this is a school project we are working on. It's a private assignment where we can't seek assistance outside of the class.

**Comment by lodenrogue** [comment]
Fair enough. Just be aware that tagging your issues with `good-first-issue` will alert everyone searching for that on github. That's how I found your project.

**Comment by truppeiner** [comment]
I wasn't aware of that, thanks for the heads up! I'll go ahead and remove the tags.
